// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        description: 'Start here to get up and running with Mailinator.',
      },
      items: ['intro','quickstart','install','gettingaround']
    },
    {
      type: 'category',
      label: 'Core Concepts',
      link: {
        type: 'generated-index',
        description: 'Learn about the core concepts of Mailinator.',
      },
      items: ['core/privatemailbox','core/publicmailbox','core/messagedelivery']
    },
    {
      type: 'category',
      label: 'Features',
      link: {
        type: 'generated-index',
        description: 'Learn about how Mailinator can help automate your email testing workflows.',
      },
      items: ['features/authenticatorinator','features/smtp-logs','features/streaming','features/sso','features/universal-idp','features/webhooks','features/twiliowebhooks']
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        description: 'Learn the essentials to make the most of Mailinator.',
      },
      items: ['guides/goodinboxnames','guides/inject-message', 'guides/injectVSwebhook','guides/webhook4sms']
    },
    {
      type: 'category',
      label: 'Test Automation',
      link: {
        type: 'generated-index',
        description: "You can integrate Mailinator into any testing framework or project, regardless of the programming language it's written in.",
      },
      items: [
        'test-automation/cypress',
        'test-automation/playwright',
        'test-automation/postman',
        'test-automation/selenium',
        'test-automation/vibium',
        'test-automation/webdriverio',
      ]
    },
    {
      type: 'category',
      label: 'AI Agents',
      link: {
        type: 'generated-index',
        description: 'Use Mailinator inboxes, private domains, CLI tooling, and MCP workflows with AI agents.',
      },
      items: [
        'ai-agents/mailinator-cli',
        'ai-agents/mailinator-mcp',
        'ai-agents/agent-safety-privacy',
        'ai-agents/agent-recipes',
      ]
    },
    {
      type: 'category',
      label: 'SDKs',
      link: {
        type: 'generated-index',
        description: 'Use our SDKs to integrate Mailinator into your applications quickly.',
      },
      items: ['sdks/overview', 'sdks/javascript-sdk', 'sdks/typescript-sdk','sdks/ruby-and-javascript-1.1.0']
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      link: {
        type: 'generated-index',
        description: 'Find solutions to common issues and get help with Mailinator.',
      },
      items: ['troubleshooting/commonissues']
    }
  ],
  apiSidebar: [],
};

// If a generated sidebar slice exists, prefer it. This file runs in Node.js.
try {
  // Use the plugin-generated CommonJS sidebar if present
  // (generated at `docs/api/sidebar.cjs` by the OpenAPI plugin or conversion script)
  // The generated file exports an array of items for the sidebar.
  // eslint-disable-next-line global-require
  const generated = require('./docs/api/sidebar.cjs');
  sidebars.apiSidebar = generated;
} catch (e) {
  // Fallback to an autogenerated sidebar from the filesystem
  sidebars.apiSidebar = [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ];
}

export default sidebars;
