name: Docs CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Lint OpenAPI spec
        run: npx @redocly/cli lint openapi/mailinator-api.yaml

      - name: Install deps (website)
        working-directory: website
        run: npm ci

      - name: Build docs (website)
        working-directory: website
        run: npm run build
